### ISSUE TITLE
[V8] Shop is not functional and Bank account information not available

### ISSUE THREAD

**Issue by sharkutz** [odoo-romania/odoo#1]
I've switch to the latest fix from 16th of March, wanted to try the odoo_ro version but when I try to access the shop it doesn't work. I've installed from l10n_ro_config most of the modules- no error.

Error message displayed:
Programming error: column res_partner_bank.currency_id does not exist
LINE 1: ...tner_bank"."sequence","res_partner_bank"."footer","res_partn...
                                                             ^
, in query  SELECT "res_partner_bank"."bank_name","res_partner_bank"."acc_number","res_partner_bank"."partner_id","res_partner_bank"."sequence","res_partner_bank"."footer","res_partner_bank"."currency_id","res_partner_bank"."id","res_partner_bank"."company_id","res_partner_bank"."state" FROM "res_partner_bank"
                        WHERE "res_partner_bank".id IN %s AND ((("res_partner_bank"."company_id" in (%s))  OR  ("res_partner_bank"."company_id" in (%s)))  OR  "res_partner_bank"."company_id" IS NULL )  ORDER BY "res_partner_bank"."sequence"

**Comment by feketemihai** [comment]
And you are using this code as a base for the l10n-branch?
